##############################################################
# This playbook contains all the tasks to generate a key and to encrypt
# and decrypt templates from a source directory.
##############################################################
---
- hosts: all
  vars:
    key_id: "alias/terraform"
    cli_json: "{{ playbook_dir }}/cli.json"
    key_spec: AES_256
    key_output: "{{ playbook_dir }}/keys/kms.json"
    template_dir: "{{ playbook_dir }}/templates"
    encrypted_dir: "{{ playbook_dir }}/encrypted"
    decrypted_dir: "{{ playbook_dir }}/decrypted"
    secrets_file: "{{ playbook_dir }}/secrets.yml"
  tasks:
    ##############################
    # Include secrets
    ##############################
    - include_tasks: tasks/secrets.yml
    # vars: secrets_file
    ##############################
    # Generate AES key with KMS
    ##############################
    - include_tasks: tasks/generate_key.yml
      vars:
        output: "{{ key_output }}"
    ##############################
    # Read AES key
    ##############################
    - include_tasks: tasks/read_key.yml
      vars:
        key_file: "{{ key_output }}"
        fact_key: "key_hex"
    ##############################
    # Encrypt template files from a source directory to a destination directory
    ##############################
    - include_tasks: tasks/encrypt_directory.yml
      # variables: template_dir, template_dir

    ##############################
    # Decrypt all files in a directory into a destination directory
    ##############################
    - include_tasks: tasks/decrypt_directory.yml
      # variables: encrypted_dir, decrypted_dir
