##############################################################
# This playbook contains all the tasks to generate a key and to encrypt
# and decrypt the entire decrypted vault.
##############################################################
---
- hosts: all
  vars:
    key_id: "alias/terraform"
    cli_json: "{{ playbook_dir }}/cli.json"
    key_spec: AES_256
    key_output: "{{ playbook_dir }}/keys/kms.json"
    vault_file: "{{ playbook_dir }}/secrets.yml"
    encrypted_vault_file: "{{ playbook_dir }}/secrets.encrypted.yml"
    decrypted_vault_file: "{{ playbook_dir }}/secrets.decrypted.yml"
    overwrite: false
  tasks:
    - include_role:
        name: filters
      tags:
        - always
    ##############################
    # Generate AES key with KMS
    ##############################
    - include_tasks: tasks/generate_key.yml
      vars:
        output: "{{ key_output }}"
      tags:
        - generate_key
    ##############################
    # Read AES key
    ##############################
    - include_tasks: tasks/read_key.yml
      vars:
        key_file: "{{ key_output }}"
        fact_key: "key_hex"
      tags:
        - encrypt
        - decrypt
    ##############################
    # Encrypt template files from a source directory to a destination directory
    ##############################
    - include_tasks: tasks/encrypt_vault.yml
      # variables: vault_file, encrypted_vault_file
      tags:
        - encrypt
    ##############################
    # Decrypt all files in a directory into a destination directory
    ##############################
    - include_tasks: tasks/decrypt_vault.yml
      # variables: encrypted_vault_file, decrypted_vault_file
      tags:
        - decrypt
