---
##############################
# Decrypt all files in a directory into a destination directory
##############################
- name: Decrypt encrypted secrets files
  block:
  - name: Make directories in decrypted directory
    file:
      state: directory
      path: "{{ decrypted_dir }}/{{ item.path }}"
    with_filetree: "{{ encrypted_dir }}"
    when: item.state == 'directory'
  - name: Decrypt data
    include_role:
      name: aes-decrypt
    vars:
      plaintext: "{{ decrypted_dir }}/{{ item.path }}"
      ciphertext: "{{ item.src }}"
    with_filetree: "{{ encrypted_dir }}"
    when: item.state == 'file'
  tags:
    - decrypt
