---
##############################
# Encrypt template files from a source directory to a destination directory
##############################
- name: Encrypt template files
  block:
  - name: Temporary Directory for rendered templates
    tempfile:
      state: directory
    register: template_rendered
  - name: Create sub-directories for rendered templates
    file:
      state: directory
      path: "{{ template_rendered.path }}/{{ item.path }}"
    with_filetree: "{{ template_dir }}"
    when: item.state == 'directory'
  - name: Render template
    template:
      src: "{{ item.src }}"
      dest: "{{ template_rendered.path }}/{{ item.path }}"
    with_filetree: "{{ template_dir }}"
    when: item.state == 'file'
  - name: Make directories in encrypted directory
    file:
      state: directory
      path: "{{ encrypted_dir }}/{{ item.path }}"
    with_filetree: "{{ template_dir }}"
    when: item.state == 'directory'
  # I would like to use an AEAD scheme but `openssl enc` does not support AEAD
  - name: Encrypt data
    include_role:
      name: aes-encrypt
    vars:
      plaintext: "{{ item.src }}"
      ciphertext: "{{ encrypted_dir }}/{{ item.path }}"
    with_filetree: "{{ template_dir }}"
    when: item.state == 'file'
  tags:
    - encrypt
